server:
  listen: 3001 # Port where the mock server will run
  workers: 1 # Number of workers (not used in the mock server but included for consistency)

  upstreams:
    - id: upstream1
      url: http://localhost:3001/data # Mock endpoint for successful response
    - id: upstream2
      url: http://localhost:3001/fail # Mock endpoint for failure

  headers:
    - key: "x-forward-for"
      value: "$ip"
    - key: "Authorization"
      value: "Bearer xyz"

  rules:
    - path: /test
      upstreams:
        - upstream2 # This will simulate a failure
    - path: /
      upstreams:
        - upstream1 # This will simulate a successful response
